import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import React from 'react';

export const metadata: Metadata = {
    title: 'NEXTjs 15 + NEXTui template',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="en"
            suppressHydrationWarning>
            <body className={`${GeistSans.className} container mx-auto`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
